[project]
name = "mindspring"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.17.2",
    "asyncpg>=0.31.0",
    "celery>=5.6.2",
    "crawl4ai>=0.7.8",
    "croniter>=6.0.0",
    "fastapi[standard]>=0.128.0",
    "flower>=2.0.1",
    "pydantic>=2.12.5",
    "python-simhash>=0.1.0",
    "redis>=7.1.0",
    "sqlalchemy>=2.0.45",
    "turboscraper",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]

[tool.uv.workspace]
members = [
    "libs/TurboScraper",
]

[tool.uv.sources]
turboscraper = { workspace = true }
