[pytest]
testpaths = tests
pythonpath= .
asyncio_mode = auto
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --strict-markers
markers =
    asyncio: mark test as async
    slow: mark test as slow running
    integration: mark test as integration test
    stress: mark test as stress test