"""add metadata

Revision ID: 190b958372f3
Revises: b4f059a2d730
Create Date: 2026-01-16 10:52:24.275188

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "190b958372f3"
down_revision: Union[str, Sequence[str], None] = "b4f059a2d730"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scraped_content", sa.Column("meta_data", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scraped_content", "meta_data")
    # ### end Alembic commands ###
