"""feat playwright_timeout and timezone

Revision ID: 8580b0d4e78b
Revises: c502b084113b
Create Date: 2026-01-08 20:17:59.266508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8580b0d4e78b"
down_revision: Union[str, Sequence[str], None] = "c502b084113b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "websites", sa.Column("timezone", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "websites", sa.Column("playwright_timeout", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("websites", "playwright_timeout")
    op.drop_column("websites", "timezone")
    # ### end Alembic commands ###
