"""Initial migration

Revision ID: 99e27c700af7
Revises: 
Create Date: 2026-01-03 20:38:33.235655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e27c700af7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('white_listed_domain', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('black_listed_domain', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('white_listed_path_patterns', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('black_listed_path_patterns', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('respect_robots', sa.Boolean(), nullable=True),
    sa.Column('max_concurrent', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('max_depth', sa.Integer(), nullable=True),
    sa.Column('rate_limiting_delay', sa.Integer(), nullable=True),
    sa.Column('user_agents', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('scraping_schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('id = 1', name='singleton_website_constraint'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_domain'), 'websites', ['domain'], unique=True)
    op.create_table('scraped_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('scrape_status', sa.String(), nullable=True),
    sa.Column('last_scraped', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_resources_id'), 'scraped_resources', ['id'], unique=False)
    op.create_index(op.f('ix_scraped_resources_scrape_status'), 'scraped_resources', ['scrape_status'], unique=False)
    op.create_index(op.f('ix_scraped_resources_url'), 'scraped_resources', ['url'], unique=False)
    op.create_index(op.f('ix_scraped_resources_website_id'), 'scraped_resources', ['website_id'], unique=False)
    op.create_table('scraped_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('dense_embeddings', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('sparse_embeddings', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['scraped_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_content_id'), 'scraped_content', ['id'], unique=False)
    op.create_index(op.f('ix_scraped_content_resource_id'), 'scraped_content', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_content_resource_id'), table_name='scraped_content')
    op.drop_index(op.f('ix_scraped_content_id'), table_name='scraped_content')
    op.drop_table('scraped_content')
    op.drop_index(op.f('ix_scraped_resources_website_id'), table_name='scraped_resources')
    op.drop_index(op.f('ix_scraped_resources_url'), table_name='scraped_resources')
    op.drop_index(op.f('ix_scraped_resources_scrape_status'), table_name='scraped_resources')
    op.drop_index(op.f('ix_scraped_resources_id'), table_name='scraped_resources')
    op.drop_table('scraped_resources')
    op.drop_index(op.f('ix_websites_domain'), table_name='websites')
    op.drop_table('websites')
    # ### end Alembic commands ###
