"""server_onupdate to onupdate

Revision ID: a32396a2ebba
Revises: 99e27c700af7
Create Date: 2026-01-04 20:43:58.387767

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a32396a2ebba"
down_revision: Union[str, Sequence[str], None] = "99e27c700af7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
