"""remove embeddings and add content hash

Revision ID: b4f059a2d730
Revises: dfbda64b6509
Create Date: 2026-01-16 10:39:37.228632

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b4f059a2d730"
down_revision: Union[str, Sequence[str], None] = "dfbda64b6509"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scraped_content",
        sa.Column("content_hash", sa.String(length=128), nullable=False),
    )
    op.alter_column(
        "scraped_content", "resource_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "scraped_content",
        "content",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=False,
    )
    op.create_index(
        op.f("ix_scraped_content_content_hash"),
        "scraped_content",
        ["content_hash"],
        unique=False,
    )
    op.create_unique_constraint(
        "unique_content_hash", "scraped_content", ["content_hash"]
    )
    op.drop_constraint(
        op.f("scraped_content_resource_id_fkey"), "scraped_content", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "scraped_content",
        "scraped_resources",
        ["resource_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("scraped_content", "sparse_embeddings")
    op.drop_column("scraped_content", "dense_embeddings")
    op.create_unique_constraint(
        "scraped_resource_url_website_id", "scraped_resources", ["url", "website_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "scraped_resource_url_website_id", "scraped_resources", type_="unique"
    )
    op.add_column(
        "scraped_content",
        sa.Column(
            "dense_embeddings",
            postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "scraped_content",
        sa.Column(
            "sparse_embeddings",
            postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "scraped_content", type_="foreignkey")
    op.create_foreign_key(
        op.f("scraped_content_resource_id_fkey"),
        "scraped_content",
        "scraped_resources",
        ["resource_id"],
        ["id"],
    )
    op.drop_constraint("unique_content_hash", "scraped_content", type_="unique")
    op.drop_index(op.f("ix_scraped_content_content_hash"), table_name="scraped_content")
    op.alter_column(
        "scraped_content",
        "content",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "scraped_content", "resource_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("scraped_content", "content_hash")
    # ### end Alembic commands ###
