"""remove unupdate for last_scraped

Revision ID: c502b084113b
Revises: a32396a2ebba
Create Date: 2026-01-06 12:33:57.642108

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c502b084113b"
down_revision: Union[str, Sequence[str], None] = "a32396a2ebba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
