"""Add url column to ScrapedContent

Revision ID: dc321e7c38a2
Revises: 190b958372f3
Create Date: 2026-01-17 14:19:49.678160

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc321e7c38a2"
down_revision: Union[str, Sequence[str], None] = "190b958372f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scraped_content", sa.Column("url", sa.String(length=2048), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scraped_content", "url")
    # ### end Alembic commands ###
